# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Callysto # Website name
baseURL: 'https://example.com/' # Website URL


############################
## COMPUTATIONAL THINKING PAGE OPTIONS
############################

cascade:
  # CT options
  - _target:
      path: /computational-thinking-tests/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on dataviz post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Data viz section options
  - _target:
      path: /computational-thinking-tests/*
      kind: section
    # Change url to /dataviz/
    url: /computational-thinking-tests/
    # Set the listing view
    view: date-title-summary
############################
## DATA VIZ PAGE OPTIONS
############################

cascade:
  # Data viz options
  - _target:
      path: /dataviz/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on dataviz post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Data viz section options
  - _target:
      path: /dataviz/*
      kind: section
    # Change url to /dataviz/
    url: /dataviz/
    # Set the listing view
    view: date-title-summary

############################
## LESSON PLAN OPTIONS
############################

cascade:
  # Lesson plan options
  - _target:
      path: /lessonplan/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on lesson plan post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # lesson plan section options
  - _target:
      path: /lessonplan/*
      kind: section
    # Change url to /lessonplan/
    url: /lessonplan/
    # Set the listing view
    view: date-title-summary

############################
## Learning modules OPTIONS
############################

cascade:
  # Learning modules options
  - _target:
      path: /learningmodule/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on lesson plan post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # lesson plan section options
  - _target:
      path: /learningmodule/*
      kind: section
    # Change url to /lessonplan/
    url: /learningmodule/
    # Set the listing view
    view: date-title-summary
############################
## Starter kit & ONLINE COURSES PAGE OPTIONS
############################

cascade:
  # online courses options
  - _target:
      path: /distance-learning/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on online courses post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Data viz section options
  - _target:
      path: /distance-learning/*
      kind: section
    # Change url to /dataviz/
    url: /distance-learning/
    # Set the listing view
    view: date-title-summary

############################
## ADDITIONAL RESOURCES PAGE OPTIONS
############################

cascade:
  # ADDITIONAL resources courses options
  - _target:
      path: /additional-resources/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on online courses post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Data viz section options
  - _target:
      path: /additional-resources/*
      kind: section
    # Change url to /dataviz/
    url: /additional-resources/
    # Set the listing view
    view: date-title-summary
############################
## Blog OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /blog/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on blog post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Blog section options
  - _target:
      path: /blog/*
      kind: section
    # Change url to /blog/
    url: /blog/
    # Set the listing view
    view: date-title-summary
############################
## CONTRIBUTIONS
############################

cascade:
  # Contributions options
  - _target:
      path: /contributions/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on blog post pages?
    show_breadcrumb: false
    header:
      navbar:
        enable: true
  # Blog section options
  - _target:
      path: /contributions/*
      kind: section
    # Change url to /blog/
    url: /contributions/
    # Set the listing view
    view: date-title-summary
############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>ÃŸ
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  computational-thinking-tests: '/computational-thinking-tests/:slug/'
  learningmodule: '/learningmodule/:slug/'
  lessonplans: '/lessonplan/:slug/'
  dataviz: '/dataviz/:slug/'
  distance-learning: '/distance-learning/:slug'
  blog: '/blog/:slug/'
  additional-resources: '/additional-resources/:slug/'
  contributions: '/contributions/:slug'
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 95
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
