# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: About
    url: /#about
    weight: 10
  - name: Teacher Resources
    url: /#resources
    weight: 20
  - name: Contact
    url: /#contact
    weight: 30
  # - name: Resources
  #   weight: 40
  #   hasChildren: true
  # - parent: Resources
  #   name: Blog
  #   url: blog/
